# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Irene Olivares
tagline:          'University of Kansas'
description:      #'University of Kansas PhD Candidate in History. <a href="https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjBhK6a-aTLAhWls4MKHdf6AToQFggsMAA&url=https%3A%2F%2Fhistory.ku.edu%2Firene-olivares&usg=AFQjCNEJZs4GN_CvAhA4yl2q3O6SEyoMkg" target="_blank">Site</a> '
url:              http://Jayhawk92.github.io
baseurl:          /Jeckyll-OL-test/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
