# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Irene Olivares
tagline:          'University of Kansas'
description:      'University of Kansas <a href="http://jekyllrb.com" target="_blank">Jekyll</a> PhD Candidate in History. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://Jayhawk92.github.io
baseurl:          /Jeckyll-OL-test/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
